#!/bin/bash
# Corral: network = "broker" (runs as root, once, at box creation; the unit
# it installs runs at every boot and before every session).
#
# Egress is decided on the Mac: an allow-list HTTP(S) proxy that corral runs
# on 127.0.0.1:PORT, reachable from the guest at the Lima gateway 192.168.5.2.
# Inside the guest nftables permits only that one destination (plus loopback
# and established flows) and rejects everything else — DNS included, since the
# proxy resolves names and a resolver would be a side channel. Every tool that
# honours HTTP(S)_PROXY (apt, npm, pip, go, git over https, curl, Claude Code)
# works; anything that ignores it fails, which is the control working. The box
# user's blanket sudo grant is removed so the agent cannot lift the rule; the
# scoped `systemctl restart corral-broker.service` entry stays for the
# launcher, which re-applies the rule before every session.
#
# Lockdown waits for the end-of-provisioning marker so toolchains and agents can
# still download directly during the first boot (and on `rebuild`).
set -euo pipefail

install -d -m 0755 /etc/corral
# shellcheck disable=SC1091
. /etc/corral/broker.conf   # PORT=

cat >/etc/corral/broker.nft <<NFT_EOF
table inet corral_broker {
  chain output {
    type filter hook output priority 0; policy drop;
    oifname "lo" accept
    ct state established,related accept
    ip daddr 192.168.5.2 tcp dport ${PORT} accept
    # sshd replies to the Mac: the session that first applies this table has a
    # connection older than conntrack, so "established" alone would not match it.
    ip daddr 192.168.5.0/24 tcp sport 22 accept
    reject
  }
  chain forward {
    type filter hook forward priority 0; policy drop;
  }
}
NFT_EOF

# Proxy environment for every login shell, systemd user services and apt.
proxy="http://192.168.5.2:${PORT}"
noproxy="localhost,127.0.0.1,::1,192.168.5.0/24,host.lima.internal"
cat >/etc/profile.d/corral-proxy.sh <<PROXY_EOF
# Generated by Corral — network = "broker": egress only via the allow-list proxy on the Mac.
export HTTP_PROXY=${proxy} HTTPS_PROXY=${proxy} http_proxy=${proxy} https_proxy=${proxy}
export NO_PROXY=${noproxy} no_proxy=${noproxy}
PROXY_EOF
chmod 0644 /etc/profile.d/corral-proxy.sh
sed -i '/^\(HTTP_PROXY\|HTTPS_PROXY\|http_proxy\|https_proxy\|NO_PROXY\|no_proxy\)=/d' /etc/environment
{
  echo "HTTP_PROXY=${proxy}"; echo "HTTPS_PROXY=${proxy}"; echo "http_proxy=${proxy}"; echo "https_proxy=${proxy}"
  echo "NO_PROXY=${noproxy}"; echo "no_proxy=${noproxy}"
} >>/etc/environment
cat >/etc/apt/apt.conf.d/90corral-proxy <<APT_EOF
Acquire::http::Proxy "${proxy}";
Acquire::https::Proxy "${proxy}";
APT_EOF

cat >/opt/corral/bin/corral-broker-lockdown <<'LOCK_EOF'
#!/bin/bash
# usage: corral-broker-lockdown   (root; reads /etc/corral/broker.conf)
set -euo pipefail
# shellcheck disable=SC1091
. /etc/corral/broker.conf

# Wait for this boot's provisioning to finish (the last user-mode step writes
# the current boot_id), up to 15 minutes. A stale marker from a previous boot
# or a golden clone does not count.
boot_id=$(cat /proc/sys/kernel/random/boot_id)
deadline=$((SECONDS + 900))
until grep -qsx "$boot_id" /home/*/.corral/provisioned; do
  if ((SECONDS >= deadline)); then
    echo "corral-broker-lockdown: provisioning marker not seen after 900s; locking down anyway" >&2
    break
  fi
  sleep 2
done

nft delete table inet corral_broker 2>/dev/null || true
nft -f /etc/corral/broker.nft

# Remove the blanket sudo grant; keep the scoped corral-* restart entries.
rm -f /etc/sudoers.d/90-cloud-init-users
for u in $(getent group sudo | cut -d: -f4 | tr ',' ' ') $(getent group admin | cut -d: -f4 | tr ',' ' '); do
  gpasswd -d "$u" sudo >/dev/null 2>&1 || true
  gpasswd -d "$u" admin >/dev/null 2>&1 || true
done

echo "corral-broker-lockdown: egress only via 192.168.5.2:${PORT}; sudo grant removed"
LOCK_EOF
chmod 0755 /opt/corral/bin/corral-broker-lockdown

cat >/etc/systemd/system/corral-broker.service <<'EOF2'
[Unit]
# Restarted before every session; systemd's default 5-starts-per-10s limit would refuse the 6th.
StartLimitIntervalSec=0
# Ordered after provisioning, not inside multi-user.target: a oneshot wanted by
# multi-user.target blocks that target until it exits, cloud-final.service (which
# runs the provision scripts that write the marker this script waits for) is
# ordered after multi-user.target, and the boot deadlocks for the 900 s fallback.
# cloud-init.target is ordered after both, so the marker is already there.
After=network.target cloud-final.service
Description=Corral: broker mode (egress only via the allow-list proxy on the Mac, drop sudo)

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/opt/corral/bin/corral-broker-lockdown

[Install]
WantedBy=cloud-init.target
EOF2

cat >/etc/sudoers.d/corral-broker <<'EOF3'
ALL ALL=(root) NOPASSWD: /usr/bin/systemctl restart corral-broker.service
EOF3
chmod 0440 /etc/sudoers.d/corral-broker

systemctl daemon-reload
systemctl disable corral-broker.service >/dev/null 2>&1 || true
systemctl enable corral-broker.service >/dev/null 2>&1
# Start in the background: the unit waits for the provisioning marker, which
# this very provisioning run writes later.
systemctl start --no-block corral-broker.service
echo "[corral] broker mode installed (port ${PORT}); lockdown follows provisioning"
