package box

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// SSHHost is the ssh_config alias Lima assigns to a box.
func SSHHost(name string) string { return "lima-" + name }

// WriteSSHInclude (re)writes the Corral ssh_config fragment at path: an
// Include of every listed box's Lima ssh.config. Lima owns those files and
// rewrites them at each start, so this fragment never carries a port.
func WriteSSHInclude(path, limaHome string, names []string) error {
	sorted := append([]string(nil), names...)
	sort.Strings(sorted)
	var b strings.Builder
	b.WriteString("# Managed by corral — regenerated by `corral code`; do not edit.\n")
	b.WriteString("# Include this file from ~/.ssh/config to reach boxes as ssh lima-<box>.\n")
	for _, n := range sorted {
		fmt.Fprintf(&b, "Include %q\n", filepath.Join(limaHome, n, "ssh.config"))
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// includeLine is the exact line EnsureUserSSHInclude adds to ~/.ssh/config.
func includeLine(include string) string { return fmt.Sprintf("Include %q", include) }

// HasUserSSHInclude reports whether the ssh_config at userConfig already
// includes the Corral fragment (any quoting, anywhere in the file).
func HasUserSSHInclude(userConfig, include string) (bool, error) {
	f, err := os.Open(userConfig)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) < 2 || !strings.EqualFold(fields[0], "Include") {
			continue
		}
		for _, p := range fields[1:] {
			if strings.Trim(p, `"`) == include {
				return true, nil
			}
		}
	}
	return false, sc.Err()
}

// EnsureUserSSHInclude prepends an Include of the Corral fragment to the
// user's ssh_config (creating it if absent). It is prepended because ssh
// applies an Include inside a Host/Match block only to that block; at the top
// it is global. Idempotent. Writing here is host-side state, so callers must
// have the user's explicit consent first.
func EnsureUserSSHInclude(userConfig, include string) (changed bool, err error) {
	has, err := HasUserSSHInclude(userConfig, include)
	if err != nil || has {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(userConfig), 0o700); err != nil {
		return false, err
	}
	old, err := os.ReadFile(userConfig)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	var b strings.Builder
	b.WriteString("# Corral boxes (ssh lima-<box>); added by `corral code`.\n")
	b.WriteString(includeLine(include) + "\n")
	if len(old) > 0 {
		b.WriteString("\n")
		b.Write(old)
	}
	return true, os.WriteFile(userConfig, []byte(b.String()), 0o600)
}
